version: '3'
services:
  bot:
    container_name: spot-bot
    build: .
    links:
      - mongo
  mongo:
    container_name: spot-mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
